/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Codigo.JuegoMonopoly;

/**
 *
 * @author pc
 */
public class Principal extends javax.swing.JFrame {
    
    private JuegoMonopoly jm;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.jm = new JuegoMonopoly();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cantjugadores = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtNombreJ1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreJ2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombreJ3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombreJ4 = new javax.swing.JTextField();
        Jugar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNombreJ5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNombreJ6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setText("JUEGO MONOPOLY");

        jLabel1.setText("Cantidad de Jugadores");

        cantjugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));
        cantjugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantjugadoresActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Jugador 1");

        jLabel3.setText("Nombre Jugador 2");

        jLabel4.setText("Nombre Jugador 3");

        txtNombreJ3.setEnabled(false);

        jLabel5.setText("Nombre Jugador 4");

        txtNombreJ4.setEnabled(false);

        Jugar.setText("Lanzar Juego");
        Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre Jugador 5");

        txtNombreJ5.setEnabled(false);

        jLabel7.setText("Nombre Jugador 6");

        txtNombreJ6.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(27, 27, 27)
                            .addComponent(txtNombreJ6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(27, 27, 27)
                            .addComponent(txtNombreJ5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(Jugar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreJ4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreJ3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63)
                        .addComponent(cantjugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titulo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cantjugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreJ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombreJ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombreJ5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNombreJ6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(Jugar)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantjugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantjugadoresActionPerformed

        switch (cantjugadores.getSelectedItem().toString()){

            case "3" -> {
                txtNombreJ3.setEnabled(true);
                txtNombreJ4.setEnabled(false);
                txtNombreJ5.setEnabled(false);
                txtNombreJ6.setEnabled(false);
                break;
            }
            case "4" -> {
                txtNombreJ3.setEnabled(true);
                txtNombreJ4.setEnabled(true);
                txtNombreJ5.setEnabled(false);
                txtNombreJ6.setEnabled(false);
                break;
            }
            case "5" -> {
                txtNombreJ3.setEnabled(true);
                txtNombreJ4.setEnabled(true);
                txtNombreJ5.setEnabled(true);
                txtNombreJ6.setEnabled(false);
                break;
            }
            case "6" -> {
                txtNombreJ3.setEnabled(true);
                txtNombreJ4.setEnabled(true);
                txtNombreJ5.setEnabled(true);
                txtNombreJ6.setEnabled(true);
                break;
            }
            default -> {
                txtNombreJ3.setEnabled(false);
                txtNombreJ4.setEnabled(false);
                txtNombreJ5.setEnabled(false);
                txtNombreJ6.setEnabled(false);
                break;
            }
        }

    }//GEN-LAST:event_cantjugadoresActionPerformed

    private void JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarActionPerformed
        
        switch(cantjugadores.getSelectedItem().toString()){ 
            case "3" -> {
                jm.agregarJugador(this.txtNombreJ1.getText());
                jm.agregarJugador(this.txtNombreJ2.getText());
                jm.agregarJugador(this.txtNombreJ3.getText());
                break;
            }
            case "4" -> {
                jm.agregarJugador(this.txtNombreJ1.getText());
                jm.agregarJugador(this.txtNombreJ2.getText());
                jm.agregarJugador(this.txtNombreJ3.getText());
                jm.agregarJugador(this.txtNombreJ4.getText());
                break;
            }
            case "5" -> {
                jm.agregarJugador(this.txtNombreJ1.getText());
                jm.agregarJugador(this.txtNombreJ2.getText());
                jm.agregarJugador(this.txtNombreJ3.getText());
                jm.agregarJugador(this.txtNombreJ4.getText());
                jm.agregarJugador(this.txtNombreJ5.getText());
                break;
            }
            case "6" -> {
                jm.agregarJugador(this.txtNombreJ1.getText());
                jm.agregarJugador(this.txtNombreJ2.getText());
                jm.agregarJugador(this.txtNombreJ3.getText());
                jm.agregarJugador(this.txtNombreJ4.getText());
                jm.agregarJugador(this.txtNombreJ5.getText());
                jm.agregarJugador(this.txtNombreJ6.getText());
                break;
            }
            default -> {
                jm.agregarJugador(this.txtNombreJ1.getText());
                jm.agregarJugador(this.txtNombreJ2.getText());
                break;
            } 
        }
        
        BoardGame bg = new BoardGame(jm);
        bg.setVisible(true);      
    }//GEN-LAST:event_JugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jugar;
    private javax.swing.JComboBox<String> cantjugadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtNombreJ1;
    private javax.swing.JTextField txtNombreJ2;
    private javax.swing.JTextField txtNombreJ3;
    private javax.swing.JTextField txtNombreJ4;
    private javax.swing.JTextField txtNombreJ5;
    private javax.swing.JTextField txtNombreJ6;
    // End of variables declaration//GEN-END:variables
}
